What is Cibyl + readthedocs folder (2 commits)
rhos-infra/cibyl pull request #2
Opened 2022-02-14 10:39 UTC by dsariel

- What is Cibyl?
- Add readthedocs folder

2022-02-14 14:41 UTC, adrianfusco commented
@dsariel just a doubt, the `conf.py` file will be in another PR?

```
Running Sphinx v4.4.0

Configuration error:
config directory doesn't contain a conf.py file (/.../cibyl/docs/source)
make: *** [Makefile:20: html] Error 2
```

Thx.

2022-02-14 19:27 UTC, bregman-arie requested changes

2022-02-16 16:44 UTC, dsariel commented on docs/source/contribute.rst
> +.. _`cibyl project`: https://github.com/redhat-openstack/cibyl
Done

2022-02-16 16:53 UTC, bregman-arie requested changes

2022-02-16 16:53 UTC, bregman-arie commented on docs/source/conf.py
> +author = u'Yair Fried'
Yair Fried? :'(

2022-02-16 16:53 UTC, bregman-arie commented on docs/source/conf.py
> +htmlhelp_basename = 'infrareddoc'
infrared

2022-02-16 16:53 UTC, bregman-arie commented on docs/source/conf.py
> +     u'Yair Fried', 'manual'),
these lines as well

2022-02-16 16:53 UTC, bregman-arie commented on docs/source/conf.py
> +    (master_doc, 'infrared', u'infrared Documentation',
infrared

2022-03-08 19:08 UTC, bregman-arie commented
This is open for 3 weeks. Let's close it in the meantime to not see it in the queue. We can revisit it once it's updated.

2022-03-08 19:08 UTC, closed without merging