Support passing job name to --spec argument
rhos-infra/cibyl pull request #218
Opened 2022-05-09 15:11 UTC by cescgina

Support calling --spec job_name without any reference to the --jobs
argument. This should perform the same checks, i.e. only one job
requested and raise an error if more than one match the request.

2022-05-09 15:41 UTC, bregman-arie requested changes
Not directly related to this PR but I'm getting a misleading message when I run `cibyl --spec bla`:

```
ERROR    cibyl.orchestrator   Error in source jenkins. Full Openstack specification can be shown only for one job, please restrict the query.
```
I think spec shouldn't support patterns, only a single job name. So the error should tell Cibyl couldn't find such job

Also, running `cibyl --spec asasdasdhajsdhasd` should also fail. If you prefer to handle in a separate PR, let me know and I'll approve this change

2022-05-09 15:47 UTC, cescgina commented
It supports patterns, it's just that the error message is not very clear. I'll improve it

2022-05-10 05:26 UTC, bregman-arie requested changes
For "cibyl --spec sasdasd" it looks good: `Error in source jenkins. No job was found, please pass --spec job-name or --jobs job-name with a valid job name or pattern.`
For `cibyl --spec` it's still little bit confusing: `Error in source jenkins. Full Openstack specification can be shown only for one job, please restrict the query.` I would expect get the same error where it tells the user to specify either a job name with --spec or to use --jobs

2022-05-10 08:41 UTC, cescgina commented
Good catch, thanks! To summarize:
`cibyl --spec` shows the No job was found error
`cibyl --spec non-existing-job` shows the No job was found error
`cibyl --spec existing-unique-job` shows the spec for the job
`cibyl --spec --jobs existing-unique-job` shows the spec for the job
`cibyl --spec --jobs pattern-many-jobs` shows the `Full Openstack specification can be shown only for one job, please restrict the query
`cibyl --spec --jobs pattern-non-existing-job` shows the no jobs was found error

2022-05-10 12:37 UTC, bregman-arie approved these changes
Perfect. Thanks

2022-05-10 13:52 UTC, merged