Fix issues in run_query due to many args and envs
rhos-infra/cibyl pull request #222
Opened 2022-05-10 14:28 UTC by cescgina

Revert a recent change that swapped the order of the systems and
arguments loops in run_query method of the Orchestrator. The argument
loop must be the outermost one. Otherwise different systems might
perform different queries if, for example, one of the systems does not
have any source that supports the argument with the highest level. This
change also updates the last_level variable, to ensure that queries like
cibyl --spec --jobs do not query for jobs, since --spec is the argument
with the highest level, and --jobs acts simply as a filter.

Solves OSPCRE-472

2022-05-10 14:55 UTC, jsanemet approved these changes

2022-05-10 18:16 UTC, adrianfusco requested changes
I was testing some different commands and some of them worked but the following gives me error:

```
(venv3.9) [2022-05-10 20:14:34] {afuscoar@afuscoar} (~/.RedHat/Projects/github/cibyl) (bug_level_query)$ -> cibyl --jobs DFG-enterprise-baremetal-upgrade-16.2_from_13-3control_2compute_externalceph-regression --source jenkins --spec
INFO     cibyl.plugins        Loading plugin: openstack
Traceback (most recent call last):
  File "/home/afuscoar/.RedHat/Projects/github/cibyl/venv3.9/bin/cibyl", line 33, in <module>
    sys.exit(load_entry_point('Cibyl', 'console_scripts', 'cibyl')())
  File "/home/afuscoar/.RedHat/Projects/github/cibyl/cibyl/cli/main.py", line 119, in main
    orchestrator.run_query()
  File "/home/afuscoar/.RedHat/Projects/github/cibyl/cibyl/orchestrator.py", line 231, in run_query
    model_instances_dict = source_method(
  File "/home/afuscoar/.RedHat/Projects/github/cibyl/cibyl/sources/jenkins.py", line 539, in get_deployment
    self.add_job_info_from_artifacts(job, query_packages=True,
  File "/home/afuscoar/.RedHat/Projects/github/cibyl/cibyl/sources/jenkins.py", line 663, in add_job_info_from_artifacts
    nodes = artifact['provision']['topology'].get('nodes', {})
KeyError: 'topology'
```

Can you check it, pls? Thx!

2022-05-11 07:32 UTC, cescgina commented
I have pushed another commit with a fix for the issue, good catch @adrianfusco!

2022-05-11 08:36 UTC, bregman-arie approved these changes

2022-05-11 11:24 UTC, adrianfusco approved these changes
Now it seems to work fine, Joan. Good job.

We have another approve so I'll merge it.

2022-05-11 11:24 UTC, merged