Generate environments based on loaded configration
rhos-infra/cibyl pull request #23
Opened 2022-02-24 09:17 UTC by bregman-arie

Once the app has loaded the configuration, it has all
the information required for creating the different
Environment instances.

These environments will be later populated with information
gathered from the different sources.

2022-02-24 09:23 UTC, bregman-arie commented
@jsanemet this part mainly depends on your implementation of the Config component so I'll wait until it's merged to continue the work on it.

2022-02-28 03:09 UTC, amolkahat approved these changes

2022-02-28 09:00 UTC, adrianfusco approved these changes

2022-02-28 09:37 UTC, cescgina commented on cibyl/models/ci/system.py
> +        self.sources = AttributeValue(name='sources', attr_type=Source,
Shouldn't this be AttributeListValue?

2022-02-28 09:40 UTC, cescgina requested changes
LGTM, just left a comment

2022-02-28 10:39 UTC, bregman-arie commented on cibyl/models/ci/system.py
> +        self.sources = AttributeValue(name='sources', attr_type=Source,
True :)

2022-02-28 10:44 UTC, merged