Adding models for Zuul tests.
rhos-infra/cibyl pull request #275
Opened 2022-05-25 12:39 UTC by jsanemet

On this pull request:
- Added 'Test' model for generic test cases.
- Added 'AnsibleTest' model for tests based on Ansible tasks.
- Added 'TempestTest' model for test best on Tempest test cases.

The models are not integrated yet, just defined.

2022-05-25 12:57 UTC, bregman-arie reviewed
For me, a test should be the same whether it's running on Jenkins or Zuul. In both systems, a test has the same properties. So why are we creating Zuul-specific test models?

2022-05-25 13:03 UTC, amolkahat requested changes

2022-05-25 13:03 UTC, amolkahat commented on tests/unit/models/ci/zuul/tests/test_ansible.py
> +    def test_equality_by_reference(self):
ditto

2022-05-25 13:03 UTC, amolkahat commented on tests/unit/models/ci/zuul/tests/test_ansible.py
> +    def test_equality_by_contents(self):
ditto

2022-05-25 13:03 UTC, amolkahat commented on tests/unit/models/ci/zuul/tests/test_tempest.py
> +    def test_equality_by_reference(self):
ditto

2022-05-25 13:03 UTC, amolkahat commented on tests/unit/models/ci/zuul/tests/test_tempest.py
> +    def test_equality_by_reference(self):
Same here as well.

2022-05-25 13:13 UTC, jsanemet commented on tests/unit/models/ci/zuul/test_test.py
> +        model = Test(TestKind.UNKNOWN, Test.Data())
The classes that I have added overwrite the '__eq__' operator, so these tests make sure that I am keeping the condition you mention true. That is why I have a test explicitly for so.

2022-05-25 13:17 UTC, jsanemet commented
@bregman-arie The test models are very similar in both systems, but I have given Zuul its own model because I have had a bad experience reusing code from Jenkins before. Zuul always shows some condition that diverges from Jenkins and reusing its code is difficult.

Also, I have noticed that Zuul has more than one provider for its test cases. We talked before about those that come from Tempest, but there are also simple jobs that run a couple of Ansible commands and consider that their test. I have added test models for those two cases for now. Later on we may add more if necessary.

2022-05-25 13:25 UTC, bregman-arie commented
> @bregman-arie The test models are very similar in both systems, but I have given Zuul its own model because I have had a bad experience reusing code from Jenkins before. Zuul always shows some condition that diverges from Jenkins and reusing its code is difficult.
> 
> Also, I have noticed that Zuul has more than one provider for its test cases. We talked before about those that come from Tempest, but there are also simple jobs that run a couple of Ansible commands and consider that their test. I have added test models for those two cases for now. Later on we may add more if necessary.

I understand the experience point, the systems are indeed very different but tests is actually a point where they should be pretty much the same as both Zuul and Jenkins run the same test/automation frameworks - tempest, tobiko, ansible, ...
Let's try to balance between diverging where needed and sharing where we have such an opportunity. If we don't have a technical reason to diverge right now, let's try to share.

2022-05-25 14:31 UTC, jsanemet commented
@bregman-arie I have just updated the request so that Zuul tests inherit from Jenkins tests.

2022-05-26 06:36 UTC, amolkahat approved these changes

2022-05-26 07:39 UTC, merged