Allow query for all openstack info with spec in elastic
rhos-infra/cibyl pull request #298
Opened 2022-05-31 14:31 UTC by adrianfusco

Ask openstack information for a single job using the elasticsearch source. Example of usage: OSPCRE-356

2022-06-01 06:38 UTC, jsanemet approved these changes
Just left a small comment. Not enough to require changes, but take a look.

2022-06-01 06:38 UTC, jsanemet commented on tests/unit/sources/elasticsearch/test_api.py
> +    def test_spec_deployment(self: object):
This tests the error that happens when there are more than on job, but what about the 'for' loop that follows it. That looks more important to test.

2022-06-01 07:26 UTC, cescgina commented on cibyl/plugins/openstack/sources/elasticsearch.py
> +                raise ElasticsearchException(
This exception should inherit from SourceException

2022-06-01 07:27 UTC, cescgina requested changes
Minor issue but the ElasticSearchException does not inherit from SourceException, which causes it to not follow the exception format

2022-06-03 11:01 UTC, cescgina approved these changes
LGTM, let's unify the spec erros of elasticsearch and Jenkins in another PR, good job!

2022-06-03 11:04 UTC, merged