Updated config template
rhos-infra/cibyl pull request #49
Opened 2022-03-14 10:25 UTC by IgnacioPro

This is just an update to the configuration template displayed on the README.
The previous template would give an error when running `cibyl` or `cibyl --help`.
Ideally, those commands should run without going through the configuration file.

2022-03-14 10:28 UTC, adrianfusco approved these changes
It works fine.

2022-03-14 11:04 UTC, bregman-arie requested changes
It won't work (= you will not be able to to pull data) if you don' specify the sources. This is what I'm using:

```
environments:
  osp_phases:
    osp_jenkins:
      system_type: jenkins                                                                                                                                                   
      sources:
        osp_jenkins1:
          driver: jenkins
          username: abregman
          token: 'PERSONAL_TOKEN'
          url: 'https://SOME_JENKINS.com'
```

2022-03-14 11:07 UTC, adrianfusco commented
> It won't work (= you will not be able to pull data) if you don't specify the sources. This is what I'm using:
> 
> ```
> environments:
>   osp_phases:
>     osp_jenkins:
>       system_type: jenkins                                                                                                                                                   
>       sources:
>         osp_jenkins1:
>           driver: jenkins
>           username: abregman
>           token: 'PERSONAL_TOKEN'
>           url: 'https://SOME_JENKINS.com'
> ```

Mmm, then I have some problem because I'm not able to pull any data even if it show in the logs it's doing the requests. I'll check my side.

2022-03-14 11:18 UTC, bregman-arie commented
> pull any data even if it show in the logs it's doing the requests. I'll check my side.

I don't think it's on your side. I'm using the PR Joan submitted. At the moment, you won't be able to pull anything before that PR is merged (unless you cherry-pick it)

2022-03-14 12:33 UTC, bregman-arie commented
> > It won't work (= you will not be able to pull data) if you don't specify the sources. This is what I'm using:
> > ```
> > environments:
> >   osp_phases:
> >     osp_jenkins:
> >       system_type: jenkins                                                                                                                                                   
> >       sources:
> >         osp_jenkins1:
> >           driver: jenkins
> >           username: abregman
> >           token: 'PERSONAL_TOKEN'
> >           url: 'https://SOME_JENKINS.com'
> > ```
> 
> This was only the minimal config file for `cibyl` or `cibyl --help` not to throw errors. At least until we figure out a solution for that since I don't think we should be pulling for config file just for --help.

Sure. Let's perhaps mention it? something along "A minimal configuration file..." and perhaps some note on sources "to be able to query, one should specify sources in the following format...depends on the source type"

2022-03-15 08:28 UTC, bregman-arie requested changes

2022-03-15 08:28 UTC, bregman-arie commented on README.md
> +  osp_phases:
osp_phases is too specific for OpenStack. Perhaps "production_ci" or "production"? same for other keys

2022-03-15 12:16 UTC, bregman-arie approved these changes
Awesome, thank you

2022-03-15 12:16 UTC, merged