Enable mypy,pycodestyle,pylint
rhos-infra/cibyl pull request #85
Opened 2022-03-20 20:44 UTC by dsariel

mypy - Checks for optionally-enforced static types.
pycodestyle - Checks against some of the style conventions in PEP 8.
pylint - Checks for errors, tries to enforce a coding standard, looks for code smells.

2022-03-21 06:36 UTC, bregman-arie requested changes
1. We already run pylint
2. pycodestyle as far as I know is a subset of pylint, Why do we want to enable both?

2022-03-21 20:11 UTC, dsariel commented
> 1. We already run pylint
> 
>     2. pycodestyle as far as I know is a subset of pylint, Why do we want to enable both?

1. Changed the pull request to adhare to google python code styling for the meoment
2. with pycodestyle it is possible to find more easily stupid errors without spending too much time on pylint configuration

2022-03-21 20:32 UTC, bregman-arie approved these changes

2022-03-22 07:39 UTC, jsanemet approved these changes

2022-03-22 07:57 UTC, merged